[2024-12-30 15:49:45,132] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_catchup_and_backfill_v1.task1 scheduled__2024-12-26T00:00:00+00:00 [queued]>
[2024-12-30 15:49:45,157] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_catchup_and_backfill_v1.task1 scheduled__2024-12-26T00:00:00+00:00 [queued]>
[2024-12-30 15:49:45,157] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 15:49:45,157] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2024-12-30 15:49:45,157] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 15:49:45,202] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task1> on 2024-12-26 00:00:00+00:00
[2024-12-30 15:49:45,211] {standard_task_runner.py:52} INFO - Started process 247 to run task
[2024-12-30 15:49:45,230] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test_dag_catchup_and_backfill_v1', 'task1', 'scheduled__2024-12-26T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmp2m1qh8in', '--error-file', '/tmp/tmpuygil4xp']
[2024-12-30 15:49:45,231] {standard_task_runner.py:80} INFO - Job 4: Subtask task1
[2024-12-30 15:49:45,380] {task_command.py:370} INFO - Running <TaskInstance: test_dag_catchup_and_backfill_v1.task1 scheduled__2024-12-26T00:00:00+00:00 [running]> on host 3ce865646fe0
[2024-12-30 15:49:45,546] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=swetansu
AIRFLOW_CTX_DAG_ID=test_dag_catchup_and_backfill_v1
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2024-12-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-26T00:00:00+00:00
[2024-12-30 15:49:45,551] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-30 15:49:45,552] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo test_catchup']
[2024-12-30 15:49:45,581] {subprocess.py:85} INFO - Output:
[2024-12-30 15:49:45,588] {subprocess.py:92} INFO - test_catchup
[2024-12-30 15:49:45,589] {subprocess.py:96} INFO - Command exited with return code 0
[2024-12-30 15:49:45,636] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test_dag_catchup_and_backfill_v1, task_id=task1, execution_date=20241226T000000, start_date=20241230T154945, end_date=20241230T154945
[2024-12-30 15:49:45,726] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-12-30 15:49:45,828] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
