[2024-12-30 15:49:45,295] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_catchup_and_backfill_v1.task1 scheduled__2024-12-27T00:00:00+00:00 [queued]>
[2024-12-30 15:49:45,330] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_catchup_and_backfill_v1.task1 scheduled__2024-12-27T00:00:00+00:00 [queued]>
[2024-12-30 15:49:45,330] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 15:49:45,330] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2024-12-30 15:49:45,330] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 15:49:45,396] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task1> on 2024-12-27 00:00:00+00:00
[2024-12-30 15:49:45,408] {standard_task_runner.py:52} INFO - Started process 250 to run task
[2024-12-30 15:49:45,420] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test_dag_catchup_and_backfill_v1', 'task1', 'scheduled__2024-12-27T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpwygmguwe', '--error-file', '/tmp/tmp8czz57li']
[2024-12-30 15:49:45,421] {standard_task_runner.py:80} INFO - Job 5: Subtask task1
[2024-12-30 15:49:45,514] {task_command.py:370} INFO - Running <TaskInstance: test_dag_catchup_and_backfill_v1.task1 scheduled__2024-12-27T00:00:00+00:00 [running]> on host 3ce865646fe0
[2024-12-30 15:49:45,709] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=swetansu
AIRFLOW_CTX_DAG_ID=test_dag_catchup_and_backfill_v1
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2024-12-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-27T00:00:00+00:00
[2024-12-30 15:49:45,710] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-30 15:49:45,711] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo test_catchup']
[2024-12-30 15:49:45,756] {subprocess.py:85} INFO - Output:
[2024-12-30 15:49:45,760] {subprocess.py:92} INFO - test_catchup
[2024-12-30 15:49:45,771] {subprocess.py:96} INFO - Command exited with return code 0
[2024-12-30 15:49:45,868] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test_dag_catchup_and_backfill_v1, task_id=task1, execution_date=20241227T000000, start_date=20241230T154945, end_date=20241230T154945
[2024-12-30 15:49:45,889] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-12-30 15:49:45,941] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
