[2024-12-30 15:50:50,693] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_catchup_and_backfill_v2.task1 scheduled__2024-12-29T00:00:00+00:00 [queued]>
[2024-12-30 15:50:50,702] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_catchup_and_backfill_v2.task1 scheduled__2024-12-29T00:00:00+00:00 [queued]>
[2024-12-30 15:50:50,702] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 15:50:50,702] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2024-12-30 15:50:50,702] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 15:50:50,711] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task1> on 2024-12-29 00:00:00+00:00
[2024-12-30 15:50:50,715] {standard_task_runner.py:52} INFO - Started process 345 to run task
[2024-12-30 15:50:50,719] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test_dag_catchup_and_backfill_v2', 'task1', 'scheduled__2024-12-29T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpcd9h5hce', '--error-file', '/tmp/tmpfbi8bx96']
[2024-12-30 15:50:50,720] {standard_task_runner.py:80} INFO - Job 9: Subtask task1
[2024-12-30 15:50:50,758] {task_command.py:370} INFO - Running <TaskInstance: test_dag_catchup_and_backfill_v2.task1 scheduled__2024-12-29T00:00:00+00:00 [running]> on host 3ce865646fe0
[2024-12-30 15:50:50,815] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=swetansu
AIRFLOW_CTX_DAG_ID=test_dag_catchup_and_backfill_v2
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2024-12-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-29T00:00:00+00:00
[2024-12-30 15:50:50,816] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-30 15:50:50,817] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo test_catchup']
[2024-12-30 15:50:50,827] {subprocess.py:85} INFO - Output:
[2024-12-30 15:50:50,828] {subprocess.py:92} INFO - test_catchup
[2024-12-30 15:50:50,828] {subprocess.py:96} INFO - Command exited with return code 0
[2024-12-30 15:50:50,851] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test_dag_catchup_and_backfill_v2, task_id=task1, execution_date=20241229T000000, start_date=20241230T155050, end_date=20241230T155050
[2024-12-30 15:50:50,890] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-12-30 15:50:50,922] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
